name: 清理releases

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行清理操作

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean up old releases
        run: |
          seven_days_ago=$(date -d "7 days ago" +%Y-%m-%d)
          tags=$(git tag)
          for tag in $tags; do
              tag_date=$(git log -1 --format=%ai $tag | cut -d ' ' -f 1)
              if [[ $tag_date < $seven_days_ago ]]; then
                  git tag -d $tag
                  git push origin :refs/tags/$tag
                  echo "Deleted old release version: $tag"
              fi
          done

      - name: Commit changes
        run: |
          git add .
          git commit -m "Cleanup old releases"
          git push
