name: Clean up old workflow runs

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule to run daily

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Delete old workflow runs
        run: |
          TOKEN=$GITHUB_TOKEN
          OWNER=$GITHUB_REPOSITORY_OWNER
          REPO=$GITHUB_REPOSITORY_NAME

          runs=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/runs" | jq '.workflow_runs[] | select(.status == "completed" and .conclusion != null and .updated_at < "'$(date -d '30 days ago' --utc +%Y-%m-%dT%H:%M:%SZ)'") | .id')

          for run in $runs; do
            curl -X DELETE -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/runs/$run"
          done
